{
 "title": "Задание 2",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "Количество свободной оперативной памяти",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemAvailable_bytes * 100) / node_memory_MemTotal_bytes",
     "legendFormat": "Free memory"
    }
   ]
  },
  {
   "title": "CPU LA",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1\n", "legendFormat": "LA1" },
    { "expr": "node_load5\n", "legendFormat": "LA5" },
    { "expr": "node_load15\n", "legendFormat": "LA15" }
   ]
  },
  {
   "title": "Количество места на файловой системе.",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_avail_bytes{fstype!~\"tmpfs|overlay\"} / node_filesystem_size_bytes{fstype!~\"tmpfs|overlay\"}) * 100"
    }
   ]
  }
 ]
}