input {
  tcp {
    port => 5000
    mode => "server"
    codec => json
  }
}

filter{
    json{
        source => "json"
   }
}

output {
  elasticsearch {
    hosts => ["http://es-hot:9200"]
    index => "docker-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
